---
title: "Pm566-midterm"
author: Tao Huang
date: October 08, 2020
output: html_document

---
MIDTERM:
Narrative Through this project you will launch a portfolio of data science projects that will become seminal for your job hunt. This midterm is a stepping stone for the final project. The first step in any data analysis is to have a dataset for which you have formulated an interesting question. If you do not have a dataset to work with, you may choose one from our list of suggestions. With your dataset, formulate a clear and concise question to answer and conduct data wrangling, exploratory data analysis, and data visualization to explore/answer this question.

Deliverable: A knitted R markdown written report (.html) with embedded tables and figures that is submitted to a project-specific github repository that you create. The report should have the following sections: Introduction (provide background on your dataset and formulated question), Methods (include how and where the data were acquired, how you cleaned and wrangled the data, what tools you used for data exploration), Preliminary Results (provide summary statistics in tabular form and publication-quality figures, take a look at the kable function from knitr to write nice tables in Rmarkdown), and a brief Conclusion about what you found in terms of the formulated question.

In your report, please do not include unformatted output or dataset summaries (e.g. output from head(), str(), etc.). You should summarize these aspects of your data within the text.


>1,have a dataset...
2,formula an interesting, clear and concise question.
3,conduct data wrangling
, exploratory data analysis, 
and data visualization to explore/answer this question
*Other report requirement*
*In your report, please do not include unformatted output or dataset1 summaries (e.g. output from head(), str(), etc.).*


```{r setup}
knitr::opts_chunk$set(include  = TRUE)
```

##QUESTION
1


```{R}
library(rvest) 
library(httr) 
library(stringr)

library(data.table)
library(tidyverse)


#get lat and lon of cities(1521s) in CA
lat_lon<-GET(
  url = "https://www.mapsofworld.com/usa/states/california/lat-long.html"
)
lat_lon <- content(lat_lon,as="text")
#extract the info
lat_lon<-str_extract_all(
  lat_lon, "(?<=<td>)(.*?)(?=</td>)")        ##extract lat & lon
lat_lon<-unlist(lat_lon)
lat_lon<-lat_lon[1:4564][-762]
str(lat_lon)

lat_lon<-data.frame(matrix(data=c,ncol=3,byrow=T,dimnames=list(c() ,c("city","lat","lon") ))
                    ,stringsAsFactors = F)
lat_lon

ll<-paste(lat_lon$lat,lat_lon$lon,sep=",")
com<-data.frame(cbind(lat_lon,ll))

com[which(com$city==""),]







URL_BASE = "https://api.forecast.io/forecast/7bed1e6e8d5e3bffa65c55c1f9fa190e/"
URL_IP = "34.0322,-118.2836/"


URL <- paste(URL_BASE,URL_IP,sep="")


city<-GET(
  url = URL
)

city <- content(city,as="text") %>%  fromJSON() 
city$daily


```





















